package com.example.entity;
// Generated 24 Nov, 2020 7:51:42 PM by Hibernate Tools 5.4.18.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Friend generated by hbm2java
 */
public class Friend implements java.io.Serializable {

	private Integer id;
	private Serializable name;
	private Set friendDetails = new HashSet(0);

	public Friend() {
	}

	public Friend(Serializable name, Set friendDetails) {
		this.name = name;
		this.friendDetails = friendDetails;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Serializable getName() {
		return this.name;
	}

	public void setName(Serializable name) {
		this.name = name;
	}

	public Set getFriendDetails() {
		return this.friendDetails;
	}

	public void setFriendDetails(Set friendDetails) {
		this.friendDetails = friendDetails;
	}

}
