package com.example.entity;
// Generated 24 Nov, 2020 7:51:42 PM by Hibernate Tools 5.4.18.Final

import java.io.Serializable;

/**
 * FriendDetail generated by hbm2java
 */
public class FriendDetail implements java.io.Serializable {

	private Integer id;
	private Friend friend;
	private Serializable friendLocation;

	public FriendDetail() {
	}

	public FriendDetail(Friend friend, Serializable friendLocation) {
		this.friend = friend;
		this.friendLocation = friendLocation;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Friend getFriend() {
		return this.friend;
	}

	public void setFriend(Friend friend) {
		this.friend = friend;
	}

	public Serializable getFriendLocation() {
		return this.friendLocation;
	}

	public void setFriendLocation(Serializable friendLocation) {
		this.friendLocation = friendLocation;
	}

}
