package com.example.pojo;
// Generated 25 Nov, 2020 7:31:27 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Brands generated by hbm2java
 */
public class Brands implements java.io.Serializable {

	private int brandId;
	private String brandName;
	private String brandLocation;
	private Set productses = new HashSet(0);

	public Brands() {
	}

	public Brands(int brandId, String brandName) {
		this.brandId = brandId;
		this.brandName = brandName;
	}

	public Brands(int brandId, String brandName, String brandLocation, Set productses) {
		this.brandId = brandId;
		this.brandName = brandName;
		this.brandLocation = brandLocation;
		this.productses = productses;
	}

	public int getBrandId() {
		return this.brandId;
	}

	public void setBrandId(int brandId) {
		this.brandId = brandId;
	}

	public String getBrandName() {
		return this.brandName;
	}

	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}

	public String getBrandLocation() {
		return this.brandLocation;
	}

	public void setBrandLocation(String brandLocation) {
		this.brandLocation = brandLocation;
	}

	public Set getProductses() {
		return this.productses;
	}

	public void setProductses(Set productses) {
		this.productses = productses;
	}

}
