package com.example.pojo;
// Generated 25 Nov, 2020 7:31:27 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;

/**
 * OrderItems generated by hbm2java
 */
public class OrderItems implements java.io.Serializable {

	private OrderItemsId id;
	private Products products;
	private Orders orders;
	private int quantity;
	private BigDecimal listPrice;
	private BigDecimal discount;

	public OrderItems() {
	}

	public OrderItems(OrderItemsId id, Products products, Orders orders, int quantity, BigDecimal listPrice,
			BigDecimal discount) {
		this.id = id;
		this.products = products;
		this.orders = orders;
		this.quantity = quantity;
		this.listPrice = listPrice;
		this.discount = discount;
	}

	public OrderItemsId getId() {
		return this.id;
	}

	public void setId(OrderItemsId id) {
		this.id = id;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public BigDecimal getListPrice() {
		return this.listPrice;
	}

	public void setListPrice(BigDecimal listPrice) {
		this.listPrice = listPrice;
	}

	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

}
