package com.example.pojo;
// Generated 25 Nov, 2020 7:31:27 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products implements java.io.Serializable {

	private int productId;
	private Brands brands;
	private Categories categories;
	private String productName;
	private short modelYear;
	private BigDecimal listPrice;
	private Set stockses = new HashSet(0);
	private Set orderItemses = new HashSet(0);

	public Products() {
	}

	public Products(int productId, Brands brands, Categories categories, String productName, short modelYear,
			BigDecimal listPrice) {
		this.productId = productId;
		this.brands = brands;
		this.categories = categories;
		this.productName = productName;
		this.modelYear = modelYear;
		this.listPrice = listPrice;
	}

	public Products(int productId, Brands brands, Categories categories, String productName, short modelYear,
			BigDecimal listPrice, Set stockses, Set orderItemses) {
		this.productId = productId;
		this.brands = brands;
		this.categories = categories;
		this.productName = productName;
		this.modelYear = modelYear;
		this.listPrice = listPrice;
		this.stockses = stockses;
		this.orderItemses = orderItemses;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public Brands getBrands() {
		return this.brands;
	}

	public void setBrands(Brands brands) {
		this.brands = brands;
	}

	public Categories getCategories() {
		return this.categories;
	}

	public void setCategories(Categories categories) {
		this.categories = categories;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public short getModelYear() {
		return this.modelYear;
	}

	public void setModelYear(short modelYear) {
		this.modelYear = modelYear;
	}

	public BigDecimal getListPrice() {
		return this.listPrice;
	}

	public void setListPrice(BigDecimal listPrice) {
		this.listPrice = listPrice;
	}

	public Set getStockses() {
		return this.stockses;
	}

	public void setStockses(Set stockses) {
		this.stockses = stockses;
	}

	public Set getOrderItemses() {
		return this.orderItemses;
	}

	public void setOrderItemses(Set orderItemses) {
		this.orderItemses = orderItemses;
	}

}
