package com.example.pojo;
// Generated 25 Nov, 2020 6:51:44 PM by Hibernate Tools 5.2.12.Final

/**
 * Stocks generated by hbm2java
 */
public class Stocks implements java.io.Serializable {

	private StocksId id;
	private Products products;
	private Stores stores;
	private Integer quantity;

	public Stocks() {
	}

	public Stocks(StocksId id, Products products, Stores stores) {
		this.id = id;
		this.products = products;
		this.stores = stores;
	}

	public Stocks(StocksId id, Products products, Stores stores, Integer quantity) {
		this.id = id;
		this.products = products;
		this.stores = stores;
		this.quantity = quantity;
	}

	public StocksId getId() {
		return this.id;
	}

	public void setId(StocksId id) {
		this.id = id;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public Stores getStores() {
		return this.stores;
	}

	public void setStores(Stores stores) {
		this.stores = stores;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

}
