package com.example.entity;
// Generated 24 Nov, 2020 7:00:05 PM by Hibernate Tools 5.4.18.Final

/**
 * FriendTable generated by hbm2java
 */
public class FriendTable implements java.io.Serializable {

	private int id;
	private String friendLocation;
	private String friendName;

	public FriendTable() {
	}

	public FriendTable(int id) {
		this.id = id;
	}

	public FriendTable(int id, String friendLocation, String friendName) {
		this.id = id;
		this.friendLocation = friendLocation;
		this.friendName = friendName;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getFriendLocation() {
		return this.friendLocation;
	}

	public void setFriendLocation(String friendLocation) {
		this.friendLocation = friendLocation;
	}

	public String getFriendName() {
		return this.friendName;
	}

	public void setFriendName(String friendName) {
		this.friendName = friendName;
	}

}
