package com.example.entity;
// Generated 25 Nov, 2020 7:36:48 PM by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name = "products", schema = "production", catalog = "crm")
public class Products implements java.io.Serializable {

	private int productId;
	private Brands brands;
	private Categories categories;
	private String productName;
	private short modelYear;
	private BigDecimal listPrice;
	private Set<Stocks> stockses = new HashSet<Stocks>(0);
	private Set<OrderItems> orderItemses = new HashSet<OrderItems>(0);

	public Products() {
	}

	public Products(int productId, Brands brands, Categories categories, String productName, short modelYear,
			BigDecimal listPrice) {
		this.productId = productId;
		this.brands = brands;
		this.categories = categories;
		this.productName = productName;
		this.modelYear = modelYear;
		this.listPrice = listPrice;
	}

	public Products(int productId, Brands brands, Categories categories, String productName, short modelYear,
			BigDecimal listPrice, Set<Stocks> stockses, Set<OrderItems> orderItemses) {
		this.productId = productId;
		this.brands = brands;
		this.categories = categories;
		this.productName = productName;
		this.modelYear = modelYear;
		this.listPrice = listPrice;
		this.stockses = stockses;
		this.orderItemses = orderItemses;
	}

	@Id

	@Column(name = "product_id", unique = true, nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "brand_id", nullable = false)
	public Brands getBrands() {
		return this.brands;
	}

	public void setBrands(Brands brands) {
		this.brands = brands;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public Categories getCategories() {
		return this.categories;
	}

	public void setCategories(Categories categories) {
		this.categories = categories;
	}

	@Column(name = "product_name", nullable = false)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "model_year", nullable = false)
	public short getModelYear() {
		return this.modelYear;
	}

	public void setModelYear(short modelYear) {
		this.modelYear = modelYear;
	}

	@Column(name = "list_price", nullable = false, precision = 10)
	public BigDecimal getListPrice() {
		return this.listPrice;
	}

	public void setListPrice(BigDecimal listPrice) {
		this.listPrice = listPrice;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "products")
	public Set<Stocks> getStockses() {
		return this.stockses;
	}

	public void setStockses(Set<Stocks> stockses) {
		this.stockses = stockses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "products")
	public Set<OrderItems> getOrderItemses() {
		return this.orderItemses;
	}

	public void setOrderItemses(Set<OrderItems> orderItemses) {
		this.orderItemses = orderItemses;
	}

}
