package com.example.entity;
// Generated 25 Nov, 2020 7:36:48 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Stores generated by hbm2java
 */
@Entity
@Table(name = "stores", schema = "sales", catalog = "crm")
public class Stores implements java.io.Serializable {

	private int storeId;
	private String storeName;
	private String phone;
	private String email;
	private String street;
	private String city;
	private String state;
	private String zipCode;
	private Set<Staffs> staffses = new HashSet<Staffs>(0);
	private Set<Orders> orderses = new HashSet<Orders>(0);
	private Set<Stocks> stockses = new HashSet<Stocks>(0);

	public Stores() {
	}

	public Stores(int storeId, String storeName) {
		this.storeId = storeId;
		this.storeName = storeName;
	}

	public Stores(int storeId, String storeName, String phone, String email, String street, String city, String state,
			String zipCode, Set<Staffs> staffses, Set<Orders> orderses, Set<Stocks> stockses) {
		this.storeId = storeId;
		this.storeName = storeName;
		this.phone = phone;
		this.email = email;
		this.street = street;
		this.city = city;
		this.state = state;
		this.zipCode = zipCode;
		this.staffses = staffses;
		this.orderses = orderses;
		this.stockses = stockses;
	}

	@Id

	@Column(name = "store_id", unique = true, nullable = false)
	public int getStoreId() {
		return this.storeId;
	}

	public void setStoreId(int storeId) {
		this.storeId = storeId;
	}

	@Column(name = "store_name", nullable = false)
	public String getStoreName() {
		return this.storeName;
	}

	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}

	@Column(name = "phone", length = 25)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "street")
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "city")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", length = 10)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "zip_code", length = 5)
	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stores")
	public Set<Staffs> getStaffses() {
		return this.staffses;
	}

	public void setStaffses(Set<Staffs> staffses) {
		this.staffses = staffses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stores")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stores")
	public Set<Stocks> getStockses() {
		return this.stockses;
	}

	public void setStockses(Set<Stocks> stockses) {
		this.stockses = stockses;
	}

}
